name: atlan
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.22+2
  font_awesome_flutter: ^8.2.0
  flutter_launcher_icons: ^0.7.2
  solid_bottom_sheet: ^0.1.9
  location: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "img/image.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  uses-material-design: true


  assets:
    - img/


  fonts:
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: LobsterTwo
      fonts:
        - asset: fonts/LobsterTwo-Bold.ttf